
# HW05 - Exploring Trees/Graphs

Name : Vivek Koodli Udupa

Some facts about trees:
+ A tree is connected and contains no cycles (by definition).
+ A tree with *n* nodes has *n* - 1 edges.
+ Every node in a tree except the root has a single parent.
+ In a tree, there is a unique path between every pair of nodes. In particular, there is a unique path of ancestors from every node to the root.

In this exercise, we use Python dictionaries to represent trees, rather than constructing the linked structures explicitly. Each dictionary entry maps a parent node to a list of its children.

In [1]:
# here is a list of edges (parent, child):
T = [('Bob','Eve'),('Alice','Carol'),('Eve','Frank'),('Alice','Doug'),('Frank','Ginger'), \
         ('Eve','Howard'),('Carol','Irene'),('Frank','Jeff'),('Doug','Kathy'),('Bob','Luis'), \
         ('Alice','Bob'),('Bob','Mabel'),('Ginger','Norm'),('Howard','Oprah'),('Carol','Peter'), \
         ('Kathy','Queen'),('Mabel','Ursala'),('Luis','Ronald'),('Ginger','Sarah'),('Irene','Tom'), \
         ('Jeff','Vince'),('Peter','Wanda'),('Oprah','Xanthia'),('Norm','Yaakov'),('Luis','Zandra')]

print ('T has',len(T),'edges')
vertices = set()
for edge in T:
    s,t = edge
    vertices.add(s)
    vertices.add(t)
print ('T has',len(vertices),'vertices')

T has 25 edges
T has 26 vertices


So this could be a tree. Now lets compute the number of parents for each vertex. The result confirms that we indeed have a tree and that the root is Alice (right?).

In [2]:
np = {}
for v in vertices:
    np[v] = 0
for parent,child in T:
    np[child] += 1
print (np)

{'Ronald': 1, 'Yaakov': 1, 'Doug': 1, 'Oprah': 1, 'Frank': 1, 'Sarah': 1, 'Kathy': 1, 'Norm': 1, 'Queen': 1, 'Zandra': 1, 'Xanthia': 1, 'Tom': 1, 'Wanda': 1, 'Ginger': 1, 'Carol': 1, 'Ursala': 1, 'Howard': 1, 'Jeff': 1, 'Bob': 1, 'Luis': 1, 'Eve': 1, 'Irene': 1, 'Peter': 1, 'Mabel': 1, 'Alice': 0, 'Vince': 1}


We now construct a dictionary of pairs (p,c) where p is the parent of the list of children c

In [3]:
adjacency_map = {}
for v in vertices:
    adjacency_map[v] = []
for p,c in T:
    adjacency_map[p].append(c)

print ("node and children:")
for p in adjacency_map:
    print (p, ":", adjacency_map[p])

print ()
print (adjacency_map)

node and children:
Ronald : []
Yaakov : []
Doug : ['Kathy']
Oprah : ['Xanthia']
Frank : ['Ginger', 'Jeff']
Sarah : []
Kathy : ['Queen']
Norm : ['Yaakov']
Queen : []
Zandra : []
Xanthia : []
Tom : []
Wanda : []
Ginger : ['Norm', 'Sarah']
Carol : ['Irene', 'Peter']
Ursala : []
Howard : ['Oprah']
Jeff : ['Vince']
Bob : ['Eve', 'Luis', 'Mabel']
Luis : ['Ronald', 'Zandra']
Eve : ['Frank', 'Howard']
Irene : ['Tom']
Peter : ['Wanda']
Mabel : ['Ursala']
Alice : ['Carol', 'Doug', 'Bob']
Vince : []

{'Ronald': [], 'Yaakov': [], 'Doug': ['Kathy'], 'Oprah': ['Xanthia'], 'Frank': ['Ginger', 'Jeff'], 'Sarah': [], 'Kathy': ['Queen'], 'Norm': ['Yaakov'], 'Queen': [], 'Zandra': [], 'Xanthia': [], 'Tom': [], 'Wanda': [], 'Ginger': ['Norm', 'Sarah'], 'Carol': ['Irene', 'Peter'], 'Ursala': [], 'Howard': ['Oprah'], 'Jeff': ['Vince'], 'Bob': ['Eve', 'Luis', 'Mabel'], 'Luis': ['Ronald', 'Zandra'], 'Eve': ['Frank', 'Howard'], 'Irene': ['Tom'], 'Peter': ['Wanda'], 'Mabel': ['Ursala'], 'Alice': ['Carol', 'Doug'

In [4]:
# Example of string replication

print (5*"Hello! ")

Hello! Hello! Hello! Hello! Hello! 


In [5]:
# A recursive Depth-First traversal of a tree defined by an adjacency_map
def print_tree_depth_first(parent, adjacency_map, level=0):
    print (level*'| ', parent)
    children = adjacency_map[parent]
    for child in children:
        print_tree_depth_first(child, adjacency_map, level+1)

root = 'Alice'
print_tree_depth_first(root, adjacency_map)

 Alice
|  Carol
| |  Irene
| | |  Tom
| |  Peter
| | |  Wanda
|  Doug
| |  Kathy
| | |  Queen
|  Bob
| |  Eve
| | |  Frank
| | | |  Ginger
| | | | |  Norm
| | | | | |  Yaakov
| | | | |  Sarah
| | | |  Jeff
| | | | |  Vince
| | |  Howard
| | | |  Oprah
| | | | |  Xanthia
| |  Luis
| | |  Ronald
| | |  Zandra
| |  Mabel
| | |  Ursala


## Question 1
Extend the following breadth-first traversal function to include the generation, so that the output is like below. Do this by storing a tuple with generation and node in the queue.

In [6]:
from collections import deque 

# breadth-first traversal using a queue
def print_tree_breath_first(root, adjacency_map):
    Q = deque()
    Q.append(root)
    while len(Q)>0:
        p = Q.popleft()
        print (p)
        children = adjacency_map[p]
        for child in children:
            Q.append(child)
        

print_tree_breath_first("Alice", adjacency_map)


Alice
Carol
Doug
Bob
Irene
Peter
Kathy
Eve
Luis
Mabel
Tom
Wanda
Queen
Frank
Howard
Ronald
Zandra
Ursala
Ginger
Jeff
Oprah
Norm
Sarah
Vince
Xanthia
Yaakov


In [7]:
#MY CODE
from collections import deque 

# breadth-first traversal using a queue
def print_tree_breath_first(root, adjacency_map):
    #Main deque
    Q = deque()
    #deque to store next generation
    kids = deque()
    #Add the initial entry, ROOT
    Q.append(root)
    #initialize count to 1
    count = 1
    #Print the root without newline character in the end
    print(count, ":", root, end = "", flush = True)
    #Finds the kinds of every parent existing in Q
    while len(Q)>0:
        p = Q.popleft()
        #Get the adjacency map for the parent p
        children = adjacency_map[p]
        #Store chindren in a new deque
        for child in children:
            kids.append(child)
        #Print the current generation    
        if len(Q)==0 :
            x = []
            count += 1
            print("\n")
            print(count, ": ",end = "", flush = True)
            while len(kids)>0:
                x = kids.popleft()
                print(x, " ", end = "", flush = True)
                Q.append(x)
                
print_tree_breath_first("Alice", adjacency_map)


1 : Alice

2 : Carol  Doug  Bob  

3 : Irene  Peter  Kathy  Eve  Luis  Mabel  

4 : Tom  Wanda  Queen  Frank  Howard  Ronald  Zandra  Ursala  

5 : Ginger  Jeff  Oprah  

6 : Norm  Sarah  Vince  Xanthia  

7 : Yaakov  

8 : 

## Question 2

Write a function that checks if for the given directed graph (given by a list of edges E) root is connected to every other vertex.

In [8]:
from collections import deque 

def adjacency_map_gen(vertices,tree):
    """This function return the adjacency map for the given vertices"""
    #Define a adjacency_map array
    adjacency_map = {}
    
    #Initialize the adjacency map
    for v in vertices:
        adjacency_map[v] = []
    
    #Add corrosponding children to every parent
    for p,c in tree:
        adjacency_map[p].append(c)
    
    return adjacency_map
    
    

def vertice_gen(edge_list):
    """Generates vertices for the given edge_list"""
    vertices = set()
    for edges in edge_list:
        x,y = edges
        vertices.add(x)
        vertices.add(y)
        
    #visited list represents the status of every vertice
    #it is true of the vertice has been visited
    #initialize it to flase
    visited = [0]* len(vertices)
    
    return visited,vertices
    
def all_connected_to(edge_list, root):
    """ return true if you can reach all nodes in the graph given
    by a list of edges (edge_list) can be reached by root """
    
    # start by constructing set of vertices and a dictionary for looking up children
    
    #Construct a set of vertices
    visited,vertices = vertice_gen(edge_list)
    #above function runs in time O(n)

    #make a queue to store parents
    parent = deque()
    parent.append(root)

    adj = adjacency_map_gen(vertices, edge_list)
    # adj runs in time O(n)

    index = 0
    #Root is visited
    visited[index] = 1
    
    #The following while loop runs in time O(n^2)
    while len(parent) > 0:
        x = parent.popleft()
        children = adj[x]
        
        for child in children:
            index += 1
            if (child == root):
#                 print("Looping back")
                break
            else:
                visited[index] = 1;
                parent.append(child)  
    
    
#     print ("Final visited array: ", visited)
#     print("Is the root connected to all vertices?")
    item = 0
    #following while runs in time O(n)
    while item < len(visited) :
        if(visited[item] == 0):
            return False
        item += 1

    return True


    

In [9]:
# This function runs in time O(n^2)
# Explain ...

# The whole function runs in time O(n) + O(n) + O(n^2) + O(n). which is equivalent to O(n^2)
#Each function with single for loop takes O(n), but the while loop which contains a for loop inside it collectively takes O(n^2). Thus the overall execution time is O(n^2)

In [10]:
G = [("A","B"), ("B","C")]
print("Is graph G connected? ")
print (all_connected_to(G, "A"))
print("\n")

G2 = [("1","2"), ("A","B"), ("B","C"), ("C","A")]
print("Is graph G2 connected for root A? ")
print (all_connected_to(G2, "A"))
print("Is graph G2 connected for root 1? ")
print (all_connected_to(G2, "1"))
print("\n")

print("Is graph G3 connected? ")
G3 = [("A","B"), ("B","C"), ("C","A")]
print (all_connected_to(G3, "C"))
print("\n")

# and our graph from above?
print("Is our above mentioned graph T connected? ")
print (all_connected_to(T, "Alice"))

Is graph G connected? 
True


Is graph G2 connected for root A? 
False
Is graph G2 connected for root 1? 
False


Is graph G3 connected? 
True


Is our above mentioned graph T connected? 
True


## Question 3
We now treat the graph T from above as undirected (edges going in both directions) and construct a tree rooted in Bob. The tree will contain edges from a vertex to the parent and direct children. The result will tell us how far removed the vertices from our root Bob are.

In [11]:
root = 'Bob'
tree = {}

# construct adjacency for graph T:
adjacency_map = {}
for vertex in vertices:
    tree[vertex] = []
    adjacency_map[vertex] = []

for edge in T:
    s,t = edge
    adjacency_map[s].append(t)
    adjacency_map[t].append(s)


for p,c in T:
    tree[p].append(c)
    
# print ("OLD parents/children of Ginger:",adjacency_map['Ginger'])
# print (adjacency_map)
# print (vertices)


# now create tree as a dictionary "n maps to children(n)"


Q = deque()
Q.append(root)
# tree = adjacency_map
#Replace the old root with the new root
while len(Q)>0:
    x = Q.popleft()
    for p,item in T:
        if x == item:
            tree[x].append(p)
            tree[p].remove(x)
            Q.append(p)
            

print (tree)

{'Ronald': [], 'Yaakov': [], 'Doug': ['Kathy'], 'Oprah': ['Xanthia'], 'Frank': ['Ginger', 'Jeff'], 'Sarah': [], 'Kathy': ['Queen'], 'Norm': ['Yaakov'], 'Queen': [], 'Zandra': [], 'Xanthia': [], 'Tom': [], 'Wanda': [], 'Ginger': ['Norm', 'Sarah'], 'Carol': ['Irene', 'Peter'], 'Ursala': [], 'Howard': ['Oprah'], 'Jeff': ['Vince'], 'Bob': ['Eve', 'Luis', 'Mabel', 'Alice'], 'Luis': ['Ronald', 'Zandra'], 'Eve': ['Frank', 'Howard'], 'Irene': ['Tom'], 'Peter': ['Wanda'], 'Mabel': ['Ursala'], 'Alice': ['Carol', 'Doug'], 'Vince': []}


Execute the following two blocks to check your result:

In [12]:
print_tree_depth_first(root, tree)

 Bob
|  Eve
| |  Frank
| | |  Ginger
| | | |  Norm
| | | | |  Yaakov
| | | |  Sarah
| | |  Jeff
| | | |  Vince
| |  Howard
| | |  Oprah
| | | |  Xanthia
|  Luis
| |  Ronald
| |  Zandra
|  Mabel
| |  Ursala
|  Alice
| |  Carol
| | |  Irene
| | | |  Tom
| | |  Peter
| | | |  Wanda
| |  Doug
| | |  Kathy
| | | |  Queen


In [13]:
print_tree_breath_first(root, tree)

1 : Bob

2 : Eve  Luis  Mabel  Alice  

3 : Frank  Howard  Ronald  Zandra  Ursala  Carol  Doug  

4 : Ginger  Jeff  Oprah  Irene  Peter  Kathy  

5 : Norm  Sarah  Vince  Xanthia  Tom  Wanda  Queen  

6 : Yaakov  

7 : 

## Question 4: n queens problem
Backtracking is the technique of recursively exploring the tree that contains all the possible solutions to a problem. Choose a systematic way to explore all the possible cases. This approach should reflect a rooted tree, and the backtracking approach is a depth-first search of the rooted tree. Whenever the search has found a solution or determined that there are no further solutions on the branches below the current vertex, backtrack to the preceeding vertex. 

A classic example of a problem that can be easily solved with this approach is the n queens problem.  This problem is to determine all the possible ways to place n nonattacking queens on an n-by-n chess board. The following code provides two helpful routines for this problem and illustrates one of the solutions for the 4 queens problem.

In [14]:
import numpy as np

def build_chessboard(N):
    chessboard = np.zeros((N,N))
    return chessboard

def print_chessboard(chessboard):
    N = len(chessboard)
    for r in range(N):
        for c in range(N):
            if chessboard[r,c] == 1:
                print ('Q', end="")
            else:
                print ('.', end="")
        print ()
    print ()

# generate an empty 4x4 chessboard:
chessboard = build_chessboard(4)
print (chessboard)

# Place 4 non-attacking queens on this board
chessboard[1,0] = 1
chessboard[3,1] = 1
chessboard[0,2] = 1
chessboard[2,3] = 1

# Pretty print the resulting board
print_chessboard(chessboard)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
..Q.
Q...
...Q
.Q..



Complete the following code to solve the n queens problem by returning the total number of solutions while printing only the first five solutions.

In [15]:
def safe(chessboard, row, col):
    """Returns 1 if the location is safe for the queen"""
    if(chessboard[row,col] == 0):
        return 1
    else:
        return 0

def attack(chessboard, row, col):
    """returns the chessboard with marked attack pattern"""
    N = len(chessboard)
    
    #Vertical
    for i in range(0,N):
        if( chessboard[i, col] == 1):
            continue
        else:
            chessboard[i,col] = 3
            
        #Horizontal
    for i in range(0,N):
        if( chessboard[row, i] == 1):
            continue
        else:
            chessboard[row,i] = 3

    #Diagonal down
    offset = row - col
    for c in range(0,N):
        r = c + offset
        if(r < 0 or r > N-1):
            continue
        else:
            if(chessboard[r,c] == 1):
                continue
            else:
                chessboard[r,c] = 3;

    #Diagonal up
    offset = row + col
    for c in range(0,N):
        r = offset - c
        if(r < 0 or r > N-1):
            continue
        else:
            if(chessboard[r,c] == 1):
                continue
            else:
                chessboard[r,c] = 3;

    return chessboard

def n_queens(chessboard, col=0, count=0):
    """ given a partially filled <chessboard>, try to place a queen in column <col> and recursively fill the board.
    Finally return the number of solutions (added to <count>)"""
    N = len(chessboard)

    if(col == N):
        count += 1
        if count < 6:
            print_chessboard(chessboard)
        return count 
    
    for i in range(N):
        #If not the last col then, 
        #if safe, place the queen in that location
        if(safe(chessboard, i, col)):
            temp = chessboard.copy()
            temp[i,col] = 1
            
            #Mark the attack path of the recently placed queen
            temp = attack(temp, i, col)
           
            #Recurse into the next column
            count = n_queens(temp, col+1, count)
            
        
    
    # Examine all available squares in column <col> (value is 0), place the queen, and 
    # mark all squares under attack by that queen (use anything except 0 or 1).
    # Note: you can make a copy of a chessboard using chessboard.copy()
    #
    
    # ????
    
    return count

chessboard = build_chessboard(8)
# print(chessboard)
count = n_queens(chessboard)
print ("solutions: ", count)

Q.......
......Q.
....Q...
.......Q
.Q......
...Q....
.....Q..
..Q.....

Q.......
......Q.
...Q....
.....Q..
.......Q
.Q......
....Q...
..Q.....

Q.......
.....Q..
.......Q
..Q.....
......Q.
...Q....
.Q......
....Q...

Q.......
....Q...
.......Q
.....Q..
..Q.....
......Q.
.Q......
...Q....

.....Q..
Q.......
....Q...
.Q......
.......Q
..Q.....
......Q.
...Q....

solutions:  92


In [16]:
chessboard = build_chessboard(5)
chessboard[1,2] = 1
chessboard = attack(chessboard,1,2)
print(chessboard)

[[0. 3. 3. 3. 0.]
 [3. 3. 1. 3. 3.]
 [0. 3. 3. 3. 0.]
 [3. 0. 3. 0. 3.]
 [0. 0. 3. 0. 0.]]


In [17]:
def test(cb):
    cb[0,0]=1
    print_chessboard(cb)
    
chessboard = build_chessboard(4)
print_chessboard(chessboard)
test(chessboard.copy())# try chessboard.copy() instead
print_chessboard(chessboard)  # oooops!

....
....
....
....

Q...
....
....
....

....
....
....
....



In [18]:
def test(b):
    b=b+1
    print (b)
    
n = 1
print (n)
test(n)
print (n)

1
2
1


In [19]:
import copy
def test(b):
    b.append(1)
    print (b)
    
n = [1,2,3]
print (n)
test(copy.copy(n)) 
print (n)
test(n)
print (n)

[1, 2, 3]
[1, 2, 3, 1]
[1, 2, 3]
[1, 2, 3, 1]
[1, 2, 3, 1]


In [20]:
import copy
a=[]
copy.deepcopy(a)

[]

In [21]:
import copy

# copy makes a copy of the outer-most object, but keeps the same references to the inner
# object.
a=[2,4,[6]]
print ("before: a=", a)

b=copy.copy(a)
b[0]+=1
b[2][0]+=1

print ("after: a=",a," b=", b, " (using copy)")

# deepcopy also makes a copy of each contained element (recursively)
a=[2,4,[6]]
b=copy.deepcopy(a)
b[0]+=1
b[2][0]+=1
print ("after: a=",a," b=", b, " (using deepcopy)")


before: a= [2, 4, [6]]
after: a= [2, 4, [7]]  b= [3, 4, [7]]  (using copy)
after: a= [2, 4, [6]]  b= [3, 4, [7]]  (using deepcopy)
